### ISSUE TITLE
Are high priority messages queued or dropped?

### ISSUE THREAD

**Issue by dotnetCarpenter** [WICG/main-thread-scheduling#2]
Hi. I just saw the presentation at https://youtu.be/mDdgfyRB5kg and are confused to what happens when multiple high priority messages are dispatched. Are they queued or dropped?

For touch events, the input rate can be extremely high and we might only need the latest position. Is this handled by this proposal?

**Comment by spanicker** [comment]
Sorry for the delay.
Posted tasks are never dropped, and will be queued.
Regarding input, this proposal does not change input handling and currently no changes are proposed to input event handlers. 
Note that chrome coalesces continuous input sources (eg. mouse wheel) and aligns them before requestAnimationFrame.

**Comment by NE-SmallTown** [comment]
> Note that chrome coalesces continuous input sources (eg. mouse wheel) and aligns them before requestAnimationFrame.

Could you give more details about this?

**Comment by shaseley** [comment]
Hi @NE-SmallTown: Apologies, this got lost in the shuffle. For more info, I found a [chromestatus](https://www.chromestatus.com/feature/6192761317359616) entry about this. It has links to a design doc and old discussion thread.

Closing this issue as the APIs we're pursuing have evolved a bit. Please feel free to file new issues against the recently updated explainers, in particular the [postTask explaner](https://github.com/WICG/main-thread-scheduling/blob/master/PrioritizedPostTask.md).
