### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by NE-SmallTown** [WICG/main-thread-scheduling#4]
Seems the [timeUntilNextFrame repo](https://github.com/WICG/main-thread-scheduling/blob/a95e49d17b362d5117068bcdea583ce54493dd54/LowLevelAPIs.md#L13) doesn't exist. Maybe it should be [this](https://github.com/WICG/requestPostAnimationFrame/blob/master/explainer.md)?

**Comment by shaseley** [comment]
Thanks! This was actually replaced with [isFramePending](https://github.com/szager-chromium/isFramePending/blob/master/explainer.md), and I've updated things to reflect that.
